/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditorPanel: typeof import('./src/components/ui/EditorPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    Header: typeof import('./src/components/ui/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HUD: typeof import('./src/components/three/HUD.vue')['default']
    Inventory: typeof import('./src/components/ui/Inventory.vue')['default']
    LandScapeTip: typeof import('./src/components/ui/LandScapeTip.vue')['default']
    LoadingScreen: typeof import('./src/components/ui/LoadingScreen.vue')['default']
    ObjectControls: typeof import('./src/components/three/ObjectControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneManager: typeof import('./src/components/three/SceneManager.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
